name: gat_helper_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.3.0  # ✅ SQLite database for Flutter
  path_provider: ^2.0.15
  confetti: 0.8.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  url_launcher: ^6.1.8




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/group_game.png
    - assets/user_icon.png
    - assets/blue.png
    - assets/blue_background.png
    - assets/rectangle1.png
    - assets/student.png
    - assets/parent1.png
    - assets/parent2.png
    - assets/self_game.png
    - assets/BB.png
    - assets/AR_rectangle.png
    - assets/downblue_background.png
    - assets/downgreen_background.png
    - assets/rank1.png
    - assets/rank2.png
    - assets/rank3.png
    - assets/Pink.png
    - assets/upblue_background.png
    - assets/yellow_background.png
    - assets/Math.png
    - assets/exit_logo.png
    - assets/confetti.png
    - assets/robot_image.png
    - assets/Mathremovebgpreview.png
    - assets/rectangle.svg
    - assets/rectangle4.svg
    - assets/rectangle5.svg
    - assets/rectangle6.svg
    - assets/img_1.png
    - assets/img_2.png
    - assets/img_3.png

    - assets/img_5.png
    - assets/img_6.png
    - assets/img_7.png
    - assets/img_8.png
    - assets/img_9.png
    - assets/img_10.png
    - assets/img_11.png
    - assets/img_12.png
    - assets/img_13.png
    - assets/img_14.png
    - assets/img_15.png
    - assets/img_16.png
    - assets/img_17.png
    - assets/img_18.png
    - assets/img_19.png
    - assets/img_20.png
    - assets/img_21.png
    - assets/img_22.png
    - assets/img_23.png
    - assets/img_24.png
    - assets/img_25.png
    - assets/img_26.png
    - assets/img_27.png
    - assets/img_28.png
    - assets/img.png
    - assets/BlueNew.png
    - assets/YellowNew.png
    - assets/verbal_questions.json
    - assets/Math_questions.json
    - assets/avatar_1.png
    - assets/avatar_2.png
    - assets/avatar_3.png
    - assets/avatar_4.png
    - assets/avatar_5.png
    - assets/avatar_6.png
    - assets/avatar_7.png
    - assets/avatar_8.png
    - assets/avatar_9.png
    - assets/avatar_10.png
    - assets/avatar_11.png
    - assets/avatar_12.png
    - assets/passages_questions_new.json
    - assets/math_pic.json
    - assets/general_avatar.jpg
    - assets/avatar3.jpg
    - assets/default_avatar.jpg
